### ISSUE TITLE
[feature] more options for styling 

### ISSUE THREAD

**Issue by ctf0** [DominicVonk/VSCode-Parameter-Hints#1]
like margin and padding, similar to [php-parameter-hint](https://github.com/robertgr991/php-parameter-hint).

is that possible ?

**Comment by DominicVonk** [comment]
Sure, I will add this, and I'm also working on a caching feature for large files.

**Comment by DominicVonk** [comment]
Do you have other ideas?

**Comment by ctf0** [comment]
for styling u mean ? no, not really 🥇

**Comment by DominicVonk** [comment]
Or other features

**Comment by ctf0** [comment]
mostly about performance, as the hints sometimes stuck on large files or when there are lots of visible hints.

**Comment by DominicVonk** [comment]
Yeah I also noticed it. In the next version the performance will be increased alot when the caching is enabled

**Comment by DominicVonk** [comment]
The PHP caching is finished and I will fix the Javascript caching too. And also the styling additions.

**Comment by ctf0** [comment]
awesome

**Comment by ctf0** [comment]
the extension console log is still active, can u plz disable it ?

**Comment by DominicVonk** [comment]
Yes I will disable it tomorrow morning (from now in about 8 hours) and I will make the caching option arter so it will only be enabled when a file is larger than X characters.

**Comment by ctf0** [comment]
ok np, thanx again.

**Comment by ctf0** [comment]
`margin-vertical` doesnt work btw, it would be perfect if it accept negative as well.

**Comment by DominicVonk** [comment]
Thank you, I will make it work to show only show the hinting for the visible lines, I think this will be even better. Thanks I will change the settings to be more css like, like the minus margins

**Comment by DominicVonk** [comment]
I pushed the update. It will be online any moment.

**Comment by DominicVonk** [comment]
Can we consider this issue done?
