### ISSUE TITLE
Background and Foreground setting does not seem to exist

### ISSUE THREAD

**Issue by centigrade-julian-lang** [DominicVonk/VSCode-Parameter-Hints#16]
Hi,

first of all thanks for your great efforts on this extension - i really like it :- )

I recently tried to change the stylings of the param hints, but it didn't work:

![image](https://user-images.githubusercontent.com/17612352/97838591-ccd9a600-1ce0-11eb-8aee-bb700c4f5acf.png)

- Left: Code example, Right: Settings.json

Any ideas?

**Comment by leodr** [comment]
You have to put them under `workbench.colorCustomizations`:

```json
// settings.json

"workbench.colorCustomizations": {
    "parameterHints.hintBackground": "#37415180",
    "parameterHints.hintForeground": "#9CA3AF"
},
```
