### ISSUE TITLE
VSCode-Parameter-Hints does not handle particular case

### ISSUE THREAD

**Issue by TestUser013** [DominicVonk/VSCode-Parameter-Hints#23]
Hello,
Thanks a lot for awesome extension! Unfortunately I faced case when the extension does not display parameter hints. 

As you can see at the first screenshot these is visible hint for getViewField method but no hints for getDescription method.
![зображення](https://user-images.githubusercontent.com/13693660/118229939-8639e500-b495-11eb-89ed-50f7f36c88f0.png)

getDescription method is declared like this
![зображення](https://user-images.githubusercontent.com/13693660/118230084-be412800-b495-11eb-8383-23df4a03ec01.png)

Any advise please? 

ps: I can not share source code because of licenses.

**Comment by DominicVonk** [comment]
Hi, when you hover the function can you send me what's in it? `(property) getPage: (url: any) => Promise<any>`

**Comment by TestUser013** [comment]
Thank you for quick response. I had to replace some words from hover popup with Q character.

![зображення](https://user-images.githubusercontent.com/13693660/118234031-70c7b980-b49b-11eb-96b2-7a5477c4f5e0.png)


```
(method) com.QQQQQQ.QQQQQQ.util.descriptionservice.DescriptionResolver.getDescription(fieldIdToUpdate: string, viewController: TSHandler.IQraViewController<any>, tableName: string, codeFieldName: string, codeFieldValue: string, descriptionFieldName: string, useTranslation?: boolean): void
@description — This method is used for updating description

@param fieldIdToUpdate — the id of the field

@param viewController — the IHttpService 

@param tableName — The name

@param codeFieldName — The column

@param codeFieldValue — The value

@param descriptionFieldName — The column

@param useTranslationService — [optional - defaults to true] if true, use translation

@return — - void
```

**Comment by DominicVonk** [comment]
I will check this out

**Comment by TestUser013** [comment]
VS Code 1.60 has build-in functionality (inlay hints) so there is no needs to use VSCode-Parameter-Hints extension.
