### ISSUE TITLE
JavaScript 无法显示

### ISSUE THREAD

**Issue by KiligFei** [DominicVonk/VSCode-Parameter-Hints#26]
![image](https://user-images.githubusercontent.com/69230517/154219131-286200a0-8a51-412d-b104-a5d3a39f8f16.png)
开启这个插件就没法显示

**Comment by w88975** [comment]
@KiligFei 确认是Parameter-Hints的问题

**Comment by w88975** [comment]
@DominicVonk 
hi
when any vscode extension regist the `HoverProvider`,  this extension will be dont show the parameter hint. 

you can test this example code:

https://code.visualstudio.com/api/references/document-selector

```javascript

vscode.languages.registerHoverProvider('typescript', {
  provideHover(doc: vscode.TextDocument) {
    return new vscode.Hover('For *all* TypeScript documents.');
  }
});

```
