### ISSUE TITLE
can we disable the console log msgs ?

### ISSUE THREAD

**Issue by ctf0** [DominicVonk/VSCode-Parameter-Hints#5]

**Comment by DominicVonk** [comment]
I will release a new version this week with a new log flag. This will fix this issue, I also working on the implementation of new languages like Python and Ruby. I think this will be published end of this week. Thank you

**Comment by DominicVonk** [comment]
You can follow the progress: https://github.com/DominicVonk/VSCode-Parameter-Hints/projects/1
